/**
 * Enhanced SQL Query Agent for Natural Language to Database Conversion
 *
 * This is an improved version with:
 * - Accurate database schema
 * - Structured prompt templates
 * - Few-shot learning examples
 * - Better error handling
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { createSupabaseQueryClient } from './db-connection';
import { generateEnhancedPrompt } from './prompt-templates';
import { getQueryCache, type CachedQuery } from './query-cache';

/**
 * Query result from enhanced SQL Agent
 */
export interface QueryResult {
  success: boolean;
  sql?: string;
  data?: Array<Record<string, unknown>>;
  explanation?: string;
  error?: string;
  rowCount?: number;
}

/**
 * Tables allowed in queries (whitelist)
 */
export const ALLOWED_TABLES = [
  'players',
  'player_skills',
  'matches',
  'player_match_stats',
  'grouping_history',
] as const;

/**
 * Maximum number of rows to return
 */
const MAX_ROWS = 100;

/**
 * Structured query definition generated by AI
 */
interface StructuredQuery {
  table: string;
  select: string;
  filters?: Array<{
    column: string;
    operator: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'ilike' | 'in' | 'is';
    value: unknown;
  }>;
  order?: {
    column: string;
    ascending: boolean;
  };
  limit?: number;
  joins?: Array<{
    table: string;
    select: string;
  }>;
}

/**
 * AI Model Configuration
 */
interface AIModelConfig {
  model: string;
  temperature: number;
  maxOutputTokens: number;
}

/**
 * Enhanced SQL Query Agent class
 */
export class EnhancedSQLQueryAgent {
  private supabase: SupabaseClient | null = null;
  private initialized = false;
  private apiKey: string;
  private modelConfig: AIModelConfig;
  private cache: ReturnType<typeof getQueryCache>;
  private useCache: boolean;

  constructor(config?: { apiKey?: string; useCache?: boolean }) {
    this.apiKey = config?.apiKey || process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || '';
    this.useCache = config?.useCache ?? true;
    this.modelConfig = {
      model: 'gemini-3.1-flash-lite-preview',
      temperature: 0.2,  // Lower temperature for more deterministic outputs
      maxOutputTokens: 2048,
    };
    this.cache = getQueryCache({ enabled: this.useCache });
  }

  /**
   * Initialize Enhanced SQL Agent
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    if (!this.apiKey) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    try {
      this.supabase = createSupabaseQueryClient();
      // Verify connection with a quick query
      const { error } = await this.supabase
        .from('players')
        .select('id', { count: 'exact', head: true });

      if (error) {
        throw new Error(`Supabase connection test failed: ${error.message}`);
      }

      this.initialized = true;
      console.log('[Enhanced SQL Agent] Initialized successfully');
    } catch (error) {
      console.error('Failed to initialize Enhanced SQL Query Agent:', error);
      throw error;
    }
  }

  /**
   * Query database with a natural language question (Enhanced)
   */
  async query(question: string): Promise<QueryResult> {
    await this.initialize();

    if (!this.supabase) {
      return {
        success: false,
        error: 'SQL Agent not initialized',
      };
    }

    // Check cache first
    if (this.useCache) {
      const cached = this.cache.get(question);
      if (cached) {
        return cached.result;
      }
    }

    try {
      // Analyze query intent to determine complexity
      const intentAnalysis = this.analyzeQueryIntent(question);
      console.log('[Enhanced SQL Agent] Query intent:', intentAnalysis);

      // Generate structured query with enhanced prompt
      const structuredQuery = await this.generateStructuredQueryEnhanced(question, intentAnalysis);

      // Validate query
      if (!this.validateQuery(structuredQuery)) {
        return {
          success: false,
          error: 'Query targets forbidden tables',
        };
      }

      // Execute query
      const data = await this.executeQuery(structuredQuery);

      const result: QueryResult = {
        success: true,
        sql: this.queryToDescription(structuredQuery),
        data,
        rowCount: data.length,
        explanation: this.generateExplanation(structuredQuery, intentAnalysis),
      };

      // Cache the result
      if (this.useCache) {
        this.cache.set(question, result);
      }

      return result;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown error';
      console.error('Enhanced SQL Query Agent error:', error);
      return {
        success: false,
        error: errorMessage,
      };
    }
  }

  /**
   * Analyze query intent to understand complexity
   */
  private analyzeQueryIntent(question: string): {
    complexity: 'simple' | 'moderate' | 'complex';
    queryType: 'player_search' | 'stats_query' | 'comparison' | 'ranking' | 'unknown';
    needsJoin: boolean;
  } {
    const lowerQuestion = question.toLowerCase();

    // Detect query type
    if (lowerQuestion.includes('排名') || lowerQuestion.includes('最') || lowerQuestion.includes('top')) {
      return {
        complexity: 'simple',
        queryType: 'ranking',
        needsJoin: true,  // Ranking usually needs player name
      };
    }

    if (lowerQuestion.includes('比较') || lowerQuestion.includes('谁强')) {
      return {
        complexity: 'moderate',
        queryType: 'comparison',
        needsJoin: true,
      };
    }

    if (lowerQuestion.includes('平均') || lowerQuestion.includes('总计') || lowerQuestion.includes('统计')) {
      return {
        complexity: 'complex',
        queryType: 'stats_query',
        needsJoin: true,
      };
    }

    if (lowerQuestion.includes('最近') || lowerQuestion.includes('比赛')) {
      return {
        complexity: 'moderate',
        queryType: 'stats_query',
        needsJoin: true,
      };
    }

    if (lowerQuestion.includes('综合评分') || lowerQuestion.includes('overall')) {
      return {
        complexity: 'simple',
        queryType: 'player_search',
        needsJoin: true,
      };
    }

    if (lowerQuestion.includes('投篮') || lowerQuestion.includes('三分') || lowerQuestion.includes('二分') ||
        lowerQuestion.includes('防守') || lowerQuestion.includes('篮板')) {
      return {
        complexity: 'moderate',
        queryType: 'player_search',
        needsJoin: true,
      };
    }

    // Default to simple search
    return {
      complexity: 'simple',
      queryType: 'player_search',
      needsJoin: false,
    };
  }

  /**
   * Generate structured query with enhanced prompt
   */
  private async generateStructuredQueryEnhanced(
    question: string,
    intentAnalysis: ReturnType<typeof this.analyzeQueryIntent>
  ): Promise<StructuredQuery> {
    const { GoogleGenerativeAI } = await import('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(this.apiKey);
    const model = genAI.getGenerativeModel({
      model: this.modelConfig.model,
      generationConfig: {
        temperature: this.modelConfig.temperature,
        maxOutputTokens: this.modelConfig.maxOutputTokens,
      },
    });

    const prompt = `${generateEnhancedPrompt()}

Now process the user's question:

Question: ${question}

Please generate a structured Supabase query following the guidelines above.

Return ONLY valid JSON, no explanations.
`;

    const response = await model.generateContent(prompt);
    const text = response.response.text();

    // Parse JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error('Failed to parse AI response as JSON:', text);
      throw new Error('Failed to parse AI response as JSON');
    }

    const parsed = JSON.parse(jsonMatch[0]) as StructuredQuery;
    return parsed;
  }

  /**
   * Generate explanation for the query
   */
  private generateExplanation(
    query: StructuredQuery,
    intentAnalysis: ReturnType<typeof this.analyzeQueryIntent>
  ): string {
    const parts = [];

    if (intentAnalysis.queryType === 'ranking') {
      parts.push(`按 ${query.order?.column || '综合评分'} 降序排列`);
    }

    if (intentAnalysis.queryType === 'player_search') {
      if (query.filters && query.filters.length > 0) {
        parts.push(`筛选条件：${query.filters.map(f => `${f.column} ${f.operator} ${f.value}`).join(' AND ')}`);
      }
    }

    if (intentAnalysis.queryType === 'stats_query') {
      parts.push('查询比赛统计数据');
    }

    if (query.joins && query.joins.length > 0) {
      parts.push(`关联表：${query.joins.map(j => j.table).join(', ')}`);
    }

    return parts.join('，');
  }

  /**
   * Validate structured query
   */
  private validateQuery(query: StructuredQuery): boolean {
    // Check main table
    if (!ALLOWED_TABLES.includes(query.table as typeof ALLOWED_TABLES[number])) {
      console.warn(`Query validation failed: table "${query.table}" not allowed`);
      return false;
    }

    // Check joined tables
    if (query.joins) {
      for (const join of query.joins) {
        if (!ALLOWED_TABLES.includes(join.table as typeof ALLOWED_TABLES[number])) {
          console.warn(`Query validation failed: joined table "${join.table}" not allowed`);
          return false;
        }
      }
    }

    return true;
  }

  /**
   * Execute a structured query against Supabase database
   */
  private async executeQuery(
    query: StructuredQuery
  ): Promise<Array<Record<string, unknown>>> {
    if (!this.supabase) {
      throw new Error('Supabase client not initialized');
    }

    // Log structured query for debugging
    console.log('[Enhanced SQL Agent] Executing query:', JSON.stringify(query, null, 2));

    try {
      // Build query
      let supabaseQuery = this.supabase
        .from(query.table)
        .select(query.select);

      // Apply filters
      if (query.filters) {
        for (const filter of query.filters) {
          switch (filter.operator) {
            case 'eq':
              supabaseQuery = supabaseQuery.eq(filter.column, filter.value);
              break;
            case 'neq':
              supabaseQuery = supabaseQuery.neq(filter.column, filter.value);
              break;
            case 'gt':
              supabaseQuery = supabaseQuery.gt(filter.column, filter.value);
              break;
            case 'gte':
              supabaseQuery = supabaseQuery.gte(filter.column, filter.value);
              break;
            case 'lt':
              supabaseQuery = supabaseQuery.lt(filter.column, filter.value);
              break;
            case 'lte':
              supabaseQuery = supabaseQuery.lte(filter.column, filter.value);
              break;
            case 'like':
              supabaseQuery = supabaseQuery.like(filter.column, String(filter.value));
              break;
            case 'ilike':
              supabaseQuery = supabaseQuery.ilike(filter.column, String(filter.value));
              break;
            case 'in':
              supabaseQuery = supabaseQuery.in(filter.column, filter.value as unknown[]);
              break;
            case 'is':
              supabaseQuery = supabaseQuery.is(filter.column, filter.value as null);
              break;
          }
        }
      }

      // Apply ordering
      if (query.order) {
        supabaseQuery = supabaseQuery.order(query.order.column, {
          ascending: query.order.ascending,
        });
      }

      // Apply limit
      const limit = Math.min(query.limit || MAX_ROWS, MAX_ROWS);
      supabaseQuery = supabaseQuery.limit(limit);

      // Execute
      const { data, error } = await supabaseQuery;

      if (error) {
        throw new Error(`Supabase query error: ${error.message}`);
      }

      return (data as unknown as Array<Record<string, unknown>>) || [];
    } catch (error) {
      console.error('Failed to execute query:', error);
      throw error;
    }
  }

  /**
   * Convert a structured query to a human-readable description
   */
  private queryToDescription(query: StructuredQuery): string {
    let desc = `SELECT ${query.select} FROM ${query.table}`;

    if (query.filters && query.filters.length > 0) {
      const filterDescs = query.filters.map(
        (f) => `${f.column} ${f.operator} ${JSON.stringify(f.value)}`
      );
      desc += ` WHERE ${filterDescs.join(' AND ')}`;
    }

    if (query.order) {
      desc += ` ORDER BY ${query.order.column} ${query.order.ascending ? 'ASC' : 'DESC'}`;
    }

    if (query.limit) {
      desc += ` LIMIT ${query.limit}`;
    }

    return desc;
  }

  /**
   * Clean up resources
   */
  async cleanup(): Promise<void> {
    this.supabase = null;
    this.initialized = false;
  }

  /**
   * Get cache statistics
   */
  public getCacheStats() {
    return this.cache.getStats();
  }

  /**
   * Log cache statistics
   */
  public logCacheStats(): void {
    this.cache.logStats();
  }

  /**
   * Check if agent is initialized
   */
  isReady(): boolean {
    return this.initialized && this.supabase !== null;
  }
}

/**
 * Global singleton instance (for Vercel warm-reuse pattern)
 */
let globalEnhancedAgent: EnhancedSQLQueryAgent | null = null;

/**
 * Get or create global Enhanced SQL Agent instance
 */
export const getOrCreateEnhancedSQLAgent = (): EnhancedSQLQueryAgent => {
  if (!globalEnhancedAgent) {
    const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
    globalEnhancedAgent = new EnhancedSQLQueryAgent({ apiKey });
  }
  return globalEnhancedAgent;
};
