/**
 * Supabase Query Agent for natural language database queries
 *
 * This module provides a Query Agent that converts natural language questions
 * into Supabase queries and executes them against the database using the
 * Supabase JS client (REST API).
 *
 * Security Features:
 * - Table whitelist: only allows queries to specific tables
 * - Read-only: only SELECT-like operations allowed
 * - Query limit: max 100 rows
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { createSupabaseQueryClient } from './db-connection.js';

/**
 * Query result from SQL Agent
 */
export interface QueryResult {
  success: boolean;
  sql?: string;
  data?: Array<Record<string, unknown>>;
  explanation?: string;
  error?: string;
  rowCount?: number;
}

/**
 * Tables allowed in queries (whitelist)
 */
export const ALLOWED_TABLES = [
  'players',
  'player_skills',
  'matches',
  'player_match_stats',
  'grouping_history',
] as const;

/**
 * Maximum number of rows to return
 */
const MAX_ROWS = 100;

/**
 * Structured query definition generated by AI
 */
interface StructuredQuery {
  table: string;
  select: string;
  filters?: Array<{
    column: string;
    operator: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'ilike' | 'in' | 'is';
    value: unknown;
  }>;
  order?: {
    column: string;
    ascending: boolean;
  };
  limit?: number;
  joins?: Array<{
    table: string;
    select: string;
  }>;
  or?: {
    conditions: Array<{
      column: string;
      operator: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'ilike' | 'in' | 'is';
      value: unknown;
    }>;
  };
}

/**
 * SQL Query Agent class
 *
 * Uses Supabase JS client and Gemini AI to convert natural language questions
 * into database queries and execute them.
 */
export class SQLQueryAgent {
  private supabase: SupabaseClient | null = null;
  private initialized = false;

  /**
   * Initialize the SQL Agent
   *
   * Creates Supabase client connection.
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    try {
      this.supabase = createSupabaseQueryClient();
      // Verify connection with a quick query
      const { error } = await this.supabase
        .from('players')
        .select('id', { count: 'exact', head: true });

      if (error) {
        throw new Error(`Supabase connection test failed: ${error.message}`);
      }

      this.initialized = true;
      console.log('[SQL Agent] Initialized successfully with Supabase JS client');
    } catch (error) {
      console.error('Failed to initialize SQL Query Agent:', error);
      throw error;
    }
  }

  /**
   * Query the database with a natural language question
   *
   * @param question - Natural language question
   * @returns Query result with data and metadata
   */
  async query(question: string): Promise<QueryResult> {
    await this.initialize();

    if (!this.supabase) {
      return {
        success: false,
        error: 'SQL Agent not initialized',
      };
    }

    try {
      // Generate structured query from natural language
      const structuredQuery = await this.generateStructuredQuery(question);

      // Validate the query
      if (!this.validateQuery(structuredQuery)) {
        return {
          success: false,
          error: 'Query targets forbidden tables',
        };
      }

      // Execute query
      const data = await this.executeQuery(structuredQuery);

      return {
        success: true,
        sql: this.queryToDescription(structuredQuery),
        data,
        rowCount: data.length,
      };
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown error';
      console.error('SQL Query Agent error:', error);
      return {
        success: false,
        error: errorMessage,
      };
    }
  }

  /**
   * Generate a structured query from natural language question
   *
   * Uses Google Generative AI to generate structured query parameters.
   *
   * @param question - Natural language question
   * @returns Structured query object
   */
  private async generateStructuredQuery(question: string): Promise<StructuredQuery> {
    const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    const { GoogleGenerativeAI } = await import('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-3.1-flash-lite-preview' });

    const prompt = `
You are a database query expert. Convert the following question into a structured Supabase query.

**IMPORTANT: This is Supabase JS client, NOT raw SQL. You MUST use nested select syntax, NEVER use table aliases like "matches_1", "matches_2", etc.**

**CRITICAL SYNTAX RULES:**
1. **OR Query Syntax**: Use .or() with PostgREST format
   - Simple OR: "name.eq.张三,name.eq.李四" (comma separated conditions)
   - IN operator: "name.in.(张三,李四)" (comma separated values)
   - Complex OR: "and(name.eq.张三,position.eq.PG),name.eq.李四" (nested AND/OR)

2. **Order by SKILL columns (CRITICAL)**: When ordering by three_point_shot, two_point_shot, overall, or any player_skills column:
   - MUST use "player_skills" as main table, "players" as join
   - Example: {"table": "player_skills", "select": "*, players(name, position)", "order": {"column": "three_point_shot", "ascending": false}, "limit": 1}
   - NEVER use players as main table with order "player_skills.three_point_shot" - this causes parse errors!

3. **Order by other joined tables**: Use foreignTable format only when necessary (e.g. matches.match_date from player_match_stats)

4. **Filter by Joined Tables**: Use dot notation for foreign table columns
   - Correct: "player_skills.overall,eq.90" (filter by joined table column)
   - Wrong: "matches_1.date,eq.2024" (NEVER use aliases in filters)

**Skill ranking questions** (谁三分最准, 投篮最好, 综合最高): Use table "player_skills", select "*, players(name, position)", order by skill column directly (e.g. three_point_shot).

Available tables and their columns:
- players: id (uuid), name (text), position (text, one of: PG, SG, SF, PF, C), created_at (timestamp), updated_at (timestamp)
- player_skills: player_id (uuid, FK→players.id), two_point_shot (int), three_point_shot (int), free_throw (int), passing (int), ball_control (int), court_vision (int), perimeter_defense (int), interior_defense (int), steals (int), blocks (int), offensive_rebound (int), defensive_rebound (int), speed (int), strength (int), stamina (int), vertical (int), basketball_iq (int), teamwork (int), clutch (int), overall (int), updated_at (timestamp)
- matches: id (uuid), match_date (timestamptz), venue (text), mode (text), teams (jsonb), result (jsonb), notes (text), created_at (timestamp), updated_at (timestamp). USE match_date NOT date!
- player_match_stats: id (uuid), match_id (uuid, FK→matches.id), player_id (uuid, FK→players.id), points (int), rebounds (int), assists (int), steals (int), blocks (int), turnovers (int), fouls (int), minutes_played (int), field_goals_made (int), field_goals_attempted (int), three_pointers_made (int), three_pointers_attempted (int), free_throws_made (int), free_throws_attempted (int), plus_minus (int), efficiency_rating (float), created_at (timestamp), updated_at (timestamp)

Question: ${question}

Return a JSON object with these fields:
{
  "table": "main table to query",
  "select": "columns to select - MUST use nested select for joins",
  "filters": [
    {"column": "column_name", "operator": "eq|neq|gt|gte|lt|lte|like|ilike|in|is", "value": "value"}
  ],
  "or": {
    "conditions": [
      {"column": "column_name", "operator": "eq|neq|gt|gte|lt|lte|like|ilike|in|is", "value": "value"}
    ]
  },
  "order": {"column": "column_name", "ascending": true/false},
  "limit": number (max 100),
  "joins": [{"table": "related_table", "select": "columns from joined table"}]
}

**CRITICAL FOR OR QUERIES:**
- "or" is a SEPARATE field from "filters", NOT inside filters array
- "or" has a "conditions" array with individual filter objects
- NEVER put {"column": "or", "operator": "or", ...} in filters

**CRITICAL RULES:**
1. **NEVER use table aliases like "matches_1", "matches_2", "table_alias.column"** - This will cause "column does not exist" errors
2. **ALWAYS use nested select syntax**: "*, related_table(column1, column2)"
3. Only use tables from the allowed list: ${ALLOWED_TABLES.join(', ')}
4. For text search use "ilike" operator with % wildcards
5. **OR queries**: Use PostgREST format with .or() for complex conditions

**CORRECT EXAMPLES:**
✅ Skill ranking (谁三分最准): { "table": "player_skills", "select": "*, players(name, position)", "order": {"column": "three_point_shot", "ascending": false}, "limit": 1 }
✅ Join player_skills: { "select": "*, player_skills(overall, defense, speed)" }
✅ Join matches: { "select": "*, matches(match_date, venue)" } - USE match_date NOT date!
✅ Multiple joins: { "select": "*, player_skills(*)" } - avoid players+player_skills+player_match_stats+matches in one query
✅ Order by joined column (non-skill): { "order": {"column": "matches(match_date)", "ascending": false} } (only when main table is player_match_stats)
✅ OR query: { "or": {"conditions": [{"column": "name", "operator": "eq", "value": "张三"}, {"column": "name", "operator": "eq", "value": "李四"}]} }
✅ Compare players: { "or": {"conditions": [{"column": "name", "operator": "ilike", "value": "%骚当%"}, {"column": "name", "operator": "ilike", "value": "%黑老王%"}]} }
✅ Player data (大哥的数据): { "table": "players", "select": "*, player_skills(*)", "filters": [{"column": "name", "operator": "ilike", "value": "%大哥%"}] }

**WRONG EXAMPLES (will cause errors):**
❌ "select": "*, matches_1.date" - NO table aliases!
❌ "select": "matches.date, players.name" - NO dot notation for joins!
❌ "filters": [{"column": "matches_1.date", ...}] - NO aliases in filters!
❌ OR with wrong syntax: "or": "is.(name.ilike.张%,name.ilike.李%)" - INVALID PostgREST syntax!

**Player data queries (X的数据, 大哥的数据)**: Use simple "*, player_skills(*)" from players. NEVER use player_match_stats(*, matches(...)) with players - causes "matches_2" errors. For match stats, query from player_match_stats as main table.

**Important for Chinese player names:**
- Always use "ilike" operator with % wildcards for name matching (never "eq")
- For comparing multiple players, use OR conditions with ilike
- Example for "骚当和黑老王": OR conditions with "name.ilike.%骚当%" and "name.ilike.%黑老王%"

Position values are: PG (控卫), SG (得分后卫), SF (小前锋), PF (大前锋), C (中锋)

Return ONLY valid JSON, no explanations.
`;

    const response = await model.generateContent(prompt);
    const text = response.response.text();

    // Parse JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Failed to parse AI response as JSON');
    }

    const parsed = JSON.parse(jsonMatch[0]) as StructuredQuery;
    return parsed;
  }

  /**
   * Validate the structured query
   *
   * @param query - Structured query to validate
   * @returns true if query is safe
   */
  private validateQuery(query: StructuredQuery): boolean {
    // Check main table
    if (!ALLOWED_TABLES.includes(query.table as typeof ALLOWED_TABLES[number])) {
      console.warn(`Query validation failed: table "${query.table}" not allowed`);
      return false;
    }

    // Check joined tables
    if (query.joins) {
      for (const join of query.joins) {
        if (!ALLOWED_TABLES.includes(join.table as typeof ALLOWED_TABLES[number])) {
          console.warn(`Query validation failed: joined table "${join.table}" not allowed`);
          return false;
        }
      }
    }

    return true;
  }

  /**
   * Execute a structured query against the Supabase database
   *
   * @param query - Structured query to execute
   * @returns Query results as array of records
   */
  private async executeQuery(
    query: StructuredQuery
  ): Promise<Array<Record<string, unknown>>> {
    if (!this.supabase) {
      throw new Error('Supabase client not initialized');
    }

    // Log the structured query for debugging
    console.log('[SQL Agent] Executing query:', JSON.stringify(query, null, 2));

    try {
      // Build the query
      let supabaseQuery = this.supabase
        .from(query.table)
        .select(query.select);

      // Apply filters
      if (query.filters) {
        for (const filter of query.filters) {
          switch (filter.operator) {
            case 'eq':
              supabaseQuery = supabaseQuery.eq(filter.column, filter.value);
              break;
            case 'neq':
              supabaseQuery = supabaseQuery.neq(filter.column, filter.value);
              break;
            case 'gt':
              supabaseQuery = supabaseQuery.gt(filter.column, filter.value);
              break;
            case 'gte':
              supabaseQuery = supabaseQuery.gte(filter.column, filter.value);
              break;
            case 'lt':
              supabaseQuery = supabaseQuery.lt(filter.column, filter.value);
              break;
            case 'lte':
              supabaseQuery = supabaseQuery.lte(filter.column, filter.value);
              break;
            case 'like':
              supabaseQuery = supabaseQuery.like(filter.column, String(filter.value));
              break;
            case 'ilike':
              supabaseQuery = supabaseQuery.ilike(filter.column, String(filter.value));
              break;
            case 'in':
              supabaseQuery = supabaseQuery.in(filter.column, filter.value as unknown[]);
              break;
            case 'is':
              supabaseQuery = supabaseQuery.is(filter.column, filter.value as null);
              break;
          }
        }
      }

      // Apply OR filters (PostgREST syntax)
      if (query.or && query.or.conditions && query.or.conditions.length > 0) {
        const orConditions = query.or.conditions.map(
          (orCondition) => {
            const valueStr = orCondition.operator === 'in' && Array.isArray(orCondition.value)
              ? `${orCondition.column}.in.(${orCondition.value.join(',')})`
              : `${orCondition.column}.${orCondition.operator}.${orCondition.value}`;
            return valueStr;
          }
        ).join(',');

        supabaseQuery = supabaseQuery.or(orConditions);
      }

      // Apply ordering - Fix for foreign table columns
      // Supabase PostgREST requires table(column) format for foreign table ordering, NOT table.column
      // See: lib/db-queries.ts .order('matches(date)', { ascending: false })
      if (query.order) {
        const isJoinedColumn = query.order.column.includes('.');
        let orderColumn = query.order.column;
        if (isJoinedColumn) {
          const [foreignTable, column] = query.order.column.split('.');
          orderColumn = `${foreignTable}(${column})`;
        }

        supabaseQuery = supabaseQuery.order(orderColumn, {
          ascending: query.order.ascending,
        });
      }

      // Apply limit
      const limit = Math.min(query.limit || MAX_ROWS, MAX_ROWS);
      supabaseQuery = supabaseQuery.limit(limit);

      // Execute
      const { data, error } = await supabaseQuery;

      if (error) {
        throw new Error(`Supabase query error: ${error.message}`);
      }

      return (data as unknown as Array<Record<string, unknown>>) || [];
    } catch (error) {
      console.error('Failed to execute query:', error);
      throw error;
    }
  }

  /**
   * Convert a structured query to a human-readable description
   *
   * @param query - Structured query
   * @returns Human-readable description
   */
  private queryToDescription(query: StructuredQuery): string {
    let desc = `SELECT ${query.select} FROM ${query.table}`;

    if (query.filters && query.filters.length > 0) {
      const filterDescs = query.filters.map(
        (f) => `${f.column} ${f.operator} ${JSON.stringify(f.value)}`
      );
      desc += ` WHERE ${filterDescs.join(' AND ')}`;
    }

    if (query.or && query.or.conditions && query.or.conditions.length > 0) {
      const orDescs = query.or.conditions.map(
        (orCondition) => {
          const valueStr = orCondition.operator === 'in' && Array.isArray(orCondition.value)
            ? `${orCondition.column}.in.(${orCondition.value.join(',')})`
            : `${orCondition.column}.${orCondition.operator}.${orCondition.value}`;
          return valueStr;
        }
      );
      const prefix = query.filters && query.filters.length > 0 ? ' OR ' : ' WHERE ';
      desc += `${prefix}(${orDescs.join(' OR ')})`;
    }

    if (query.order) {
      desc += ` ORDER BY ${query.order.column} ${query.order.ascending ? 'ASC' : 'DESC'}`;
    }

    if (query.limit) {
      desc += ` LIMIT ${query.limit}`;
    }

    return desc;
  }

  /**
   * Clean up resources
   */
  async cleanup(): Promise<void> {
    this.supabase = null;
    this.initialized = false;
  }

  /**
   * Check if the agent is initialized
   */
  isReady(): boolean {
    return this.initialized && this.supabase !== null;
  }
}

/**
 * Global singleton instance (for Vercel warm-reuse pattern)
 */
let globalAgent: SQLQueryAgent | null = null;

/**
 * Get or create global SQL Agent instance
 *
 * @returns SQL Agent instance
 */
export const getOrCreateSQLAgent = (): SQLQueryAgent => {
  if (!globalAgent) {
    globalAgent = new SQLQueryAgent();
  }
  return globalAgent;
};
