/**
 * Supabase Query Agent for natural language database queries
 *
 * This module provides a Query Agent that converts natural language questions
 * into Supabase queries and executes them against the database using the
 * Supabase JS client (REST API).
 *
 * Security Features:
 * - Table whitelist: only allows queries to specific tables
 * - Read-only: only SELECT-like operations allowed
 * - Query limit: max 100 rows
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { createSupabaseQueryClient } from './db-connection.js';

/**
 * Query result from SQL Agent
 */
export interface QueryResult {
  success: boolean;
  sql?: string;
  data?: Array<Record<string, unknown>>;
  explanation?: string;
  error?: string;
  rowCount?: number;
}

/**
 * Tables allowed in queries (whitelist)
 */
export const ALLOWED_TABLES = [
  'players',
  'player_skills',
  'matches',
  'player_match_stats',
  'grouping_history',
] as const;

/**
 * Maximum number of rows to return
 */
const MAX_ROWS = 100;

/**
 * Structured query definition generated by AI
 */
interface StructuredQuery {
  table: string;
  select: string;
  filters?: Array<{
    column: string;
    operator: 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'like' | 'ilike' | 'in' | 'is';
    value: unknown;
  }>;
  order?: {
    column: string;
    ascending: boolean;
  };
  limit?: number;
  joins?: Array<{
    table: string;
    select: string;
  }>;
}

/**
 * SQL Query Agent class
 *
 * Uses Supabase JS client and Gemini AI to convert natural language questions
 * into database queries and execute them.
 */
export class SQLQueryAgent {
  private supabase: SupabaseClient | null = null;
  private initialized = false;

  /**
   * Initialize the SQL Agent
   *
   * Creates Supabase client connection.
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    try {
      this.supabase = createSupabaseQueryClient();
      // Verify connection with a quick query
      const { error } = await this.supabase
        .from('players')
        .select('id', { count: 'exact', head: true });

      if (error) {
        throw new Error(`Supabase connection test failed: ${error.message}`);
      }

      this.initialized = true;
      console.log('[SQL Agent] Initialized successfully with Supabase JS client');
    } catch (error) {
      console.error('Failed to initialize SQL Query Agent:', error);
      throw error;
    }
  }

  /**
   * Query the database with a natural language question
   *
   * @param question - Natural language question
   * @returns Query result with data and metadata
   */
  async query(question: string): Promise<QueryResult> {
    await this.initialize();

    if (!this.supabase) {
      return {
        success: false,
        error: 'SQL Agent not initialized',
      };
    }

    try {
      // Generate structured query from natural language
      const structuredQuery = await this.generateStructuredQuery(question);

      // Validate the query
      if (!this.validateQuery(structuredQuery)) {
        return {
          success: false,
          error: 'Query targets forbidden tables',
        };
      }

      // Execute query
      const data = await this.executeQuery(structuredQuery);

      return {
        success: true,
        sql: this.queryToDescription(structuredQuery),
        data,
        rowCount: data.length,
      };
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Unknown error';
      console.error('SQL Query Agent error:', error);
      return {
        success: false,
        error: errorMessage,
      };
    }
  }

  /**
   * Generate a structured query from natural language question
   *
   * Uses Google Generative AI to generate structured query parameters.
   *
   * @param question - Natural language question
   * @returns Structured query object
   */
  private async generateStructuredQuery(question: string): Promise<StructuredQuery> {
    const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    const { GoogleGenerativeAI } = await import('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });

    const prompt = `
You are a database query expert. Convert the following question into a structured Supabase query.

Available tables and their columns:
- players: id (uuid), name (text), position (text, one of: PG, SG, SF, PF, C), created_at (timestamp)
- player_skills: player_id (uuid, FK→players.id), two_point_rating (int), three_point_rating (int), free_throw_rating (int), mid_range_rating (int), layup_rating (int), dunk_rating (int), passing (int), dribbling (int), ball_handling (int), rebounding (int), defense (int), shot_blocking (int), stealing (int), post_moves (int), perimeter_defense (int), speed (int), stamina (int), strength (int), vertical (int), basketball_iq (int), overall (int)
- matches: id (uuid), date (date), venue (text), mode (text), teams (jsonb), result (jsonb), notes (text)
- player_match_stats: id (uuid), match_id (uuid, FK→matches.id), player_id (uuid, FK→players.id), points (int), rebounds (int), assists (int), steals (int), blocks (int), turnovers (int), fouls (int), minutes_played (int), efficiency_rating (float)

Question: ${question}

Return a JSON object with these fields:
{
  "table": "main table to query",
  "select": "columns to select, use * for all, use table_name(columns) for joins",
  "filters": [
    {"column": "column_name", "operator": "eq|neq|gt|gte|lt|lte|like|ilike|in|is", "value": "value"}
  ],
  "order": {"column": "column_name", "ascending": true/false},
  "limit": number (max 100),
  "joins": [{"table": "related_table", "select": "columns from joined table"}]
}

Rules:
- Only use tables from the allowed list: ${ALLOWED_TABLES.join(', ')}
- For text search use "ilike" operator with % wildcards
- For joining player_skills, use select like: "*, player_skills(overall, defense, speed)"
- For joining matches from player_match_stats, use: "*, matches(date, venue)"
- Return ONLY valid JSON, no explanations
- Position values are: PG (控卫), SG (得分后卫), SF (小前锋), PF (大前锋), C (中锋)
`;

    const response = await model.generateContent(prompt);
    const text = response.response.text();

    // Parse JSON from response
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Failed to parse AI response as JSON');
    }

    const parsed = JSON.parse(jsonMatch[0]) as StructuredQuery;
    return parsed;
  }

  /**
   * Validate the structured query
   *
   * @param query - Structured query to validate
   * @returns true if query is safe
   */
  private validateQuery(query: StructuredQuery): boolean {
    // Check main table
    if (!ALLOWED_TABLES.includes(query.table as typeof ALLOWED_TABLES[number])) {
      console.warn(`Query validation failed: table "${query.table}" not allowed`);
      return false;
    }

    // Check joined tables
    if (query.joins) {
      for (const join of query.joins) {
        if (!ALLOWED_TABLES.includes(join.table as typeof ALLOWED_TABLES[number])) {
          console.warn(`Query validation failed: joined table "${join.table}" not allowed`);
          return false;
        }
      }
    }

    return true;
  }

  /**
   * Execute a structured query against the Supabase database
   *
   * @param query - Structured query to execute
   * @returns Query results as array of records
   */
  private async executeQuery(
    query: StructuredQuery
  ): Promise<Array<Record<string, unknown>>> {
    if (!this.supabase) {
      throw new Error('Supabase client not initialized');
    }

    try {
      // Build the query
      let supabaseQuery = this.supabase
        .from(query.table)
        .select(query.select);

      // Apply filters
      if (query.filters) {
        for (const filter of query.filters) {
          switch (filter.operator) {
            case 'eq':
              supabaseQuery = supabaseQuery.eq(filter.column, filter.value);
              break;
            case 'neq':
              supabaseQuery = supabaseQuery.neq(filter.column, filter.value);
              break;
            case 'gt':
              supabaseQuery = supabaseQuery.gt(filter.column, filter.value);
              break;
            case 'gte':
              supabaseQuery = supabaseQuery.gte(filter.column, filter.value);
              break;
            case 'lt':
              supabaseQuery = supabaseQuery.lt(filter.column, filter.value);
              break;
            case 'lte':
              supabaseQuery = supabaseQuery.lte(filter.column, filter.value);
              break;
            case 'like':
              supabaseQuery = supabaseQuery.like(filter.column, String(filter.value));
              break;
            case 'ilike':
              supabaseQuery = supabaseQuery.ilike(filter.column, String(filter.value));
              break;
            case 'in':
              supabaseQuery = supabaseQuery.in(filter.column, filter.value as unknown[]);
              break;
            case 'is':
              supabaseQuery = supabaseQuery.is(filter.column, filter.value as null);
              break;
          }
        }
      }

      // Apply ordering
      if (query.order) {
        supabaseQuery = supabaseQuery.order(query.order.column, {
          ascending: query.order.ascending,
        });
      }

      // Apply limit
      const limit = Math.min(query.limit || MAX_ROWS, MAX_ROWS);
      supabaseQuery = supabaseQuery.limit(limit);

      // Execute
      const { data, error } = await supabaseQuery;

      if (error) {
        throw new Error(`Supabase query error: ${error.message}`);
      }

      return (data as unknown as Array<Record<string, unknown>>) || [];
    } catch (error) {
      console.error('Failed to execute query:', error);
      throw error;
    }
  }

  /**
   * Convert a structured query to a human-readable description
   *
   * @param query - Structured query
   * @returns Human-readable description
   */
  private queryToDescription(query: StructuredQuery): string {
    let desc = `SELECT ${query.select} FROM ${query.table}`;

    if (query.filters && query.filters.length > 0) {
      const filterDescs = query.filters.map(
        (f) => `${f.column} ${f.operator} ${JSON.stringify(f.value)}`
      );
      desc += ` WHERE ${filterDescs.join(' AND ')}`;
    }

    if (query.order) {
      desc += ` ORDER BY ${query.order.column} ${query.order.ascending ? 'ASC' : 'DESC'}`;
    }

    if (query.limit) {
      desc += ` LIMIT ${query.limit}`;
    }

    return desc;
  }

  /**
   * Clean up resources
   */
  async cleanup(): Promise<void> {
    this.supabase = null;
    this.initialized = false;
  }

  /**
   * Check if the agent is initialized
   */
  isReady(): boolean {
    return this.initialized && this.supabase !== null;
  }
}

/**
 * Global singleton instance (for Vercel warm-reuse pattern)
 */
let globalAgent: SQLQueryAgent | null = null;

/**
 * Get or create global SQL Agent instance
 *
 * @returns SQL Agent instance
 */
export const getOrCreateSQLAgent = (): SQLQueryAgent => {
  if (!globalAgent) {
    globalAgent = new SQLQueryAgent();
  }
  return globalAgent;
};
